<h1>Terms of Use</h1>
Welcome to our online store! MyClassToo.com and its associates provide their services to you subject to the following conditions. If you visit or shop within this website, you accept these conditions. Please read them carefully. 

<h2>PRIVACY</h2>
Please review our Privacy Notice, which also governs your visit to our website, to understand our practices. 

<h2>ELECTRONIC COMMUNICATIONS</h2>
When you visit MyClassToo.com or send e-mails to us, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on this site. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. 

<h2>COPYRIGHT</h2>
All content included on this site, such as text, graphics, logos, images, audio clips, digital downloads, data compilations, and software, is the property of MyClassToo.com or its content suppliers and protected by international copyright laws. The compilation of all content on this site is the exclusive property of MyClassToo.com, with copyright authorship for this collection by MyClassToo.com, and protected by international copyright laws. 

<h2>TRADE MARKS</h2>
MyClassToo.coms trademarks and trade dress may not be used in connection with any product or service that is not MyClassToo.com, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits MyClassToo.com. All other trademarks not owned by MyClassToo.com or its subsidiaries that appear on this site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by MyClassToo.com or its subsidiaries. 

<h2>LICENSE AND SITE ACCESS</h2>
MyClassToo.com grants you a limited license to access and make personal use of this site and not to download (other than page caching) or modify it, or any portion of it, except with express written consent of MyClassToo.com. This license does not include any resale or commercial use of this site or its contents: any collection and use of any product listings, descriptions, or prices: any derivative use of this site or its contents: any downloading or copying of account information for the benefit of another merchant: or any use of data mining, robots, or similar data gathering and extraction tools. This site or any portion of this site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of MyClassToo.com. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of MyClassToo.com and our associates without express written consent. You may not use any meta tags or any other "hidden text" utilizing MyClassToo.com's name or trademarks without the express written consent of MyClassToo.com. Any unauthorized use terminates the permission or license granted by MyClassToo.com. You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the home page of MyClassToo.com so long as the link does not portray MyClassToo.com, its associates, or their products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any MyClassToo.com logo or other proprietary graphic or trademark as part of the link without express written permission. 

<h2>YOUR MEMBERSHIP ACCOUNT</h2>
If you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. If you are under 18, you may use our website only with involvement of a parent or guardian. MyClassToo.com and its associates reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in their sole discretion. 

<h2>REVIEWS, COMMENTS, EMAILS, AND OTHER CONTENT</h2>
Visitors may post reviews, comments, and other content: and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. MyClassToo.com reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content. If you do post content or submit material, and unless we indicate otherwise, you grant MyClassToo.com and its associates a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant MyClassToo.com and its associates and sublicensees the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post: that the content is accurate: that use of the content you supply does not violate this policy and will not cause injury to any person or entity: and that you will indemnify MyClassToo.com or its associates for all claims resulting from content you supply. MyClassToo.com has the right but not the obligation to monitor and edit or remove any activity or content. MyClassToo.com takes no responsibility and assumes no liability for any content posted by you or any third party. 

<h2>PRODUCT DESCRIPTIONS</h2>
MyClassToo.com and its associates attempt to be as accurate as possible. However, MyClassToo.com does not warrant that product descriptions or other content of this site is accurate, complete, reliable, current, or error-free. If a product offered by MyClassToo.com itself is not as described, your sole remedy is to return it in unused condition. 

DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY THIS SITE IS PROVIDED BY MYCLASSTOO.COM ON AN "AS IS" AND "AS AVAILABLE" BASIS. MYCLASSTOO.COM MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THIS SITE OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDED ON THIS SITE. YOU EXPRESSLY AGREE THAT YOUR USE OF THIS SITE IS AT YOUR SOLE RISK. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, MYCLASSTOO.COM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. MYCLASSTOO.COM DOES NOT WARRANT THAT THIS SITE, ITS SERVERS, OR E-MAIL SENT FROM MYCLASSTOO.COM ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. MYCLASSTOO.COM WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS SITE, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS. 

<h2>APPLICABLE LAW</h2>
By visiting MyClassToo.com, you agree that the laws of the state of California, United States, without regard to principles of conflict of laws, will govern these Conditions of Use and any dispute of any sort that might arise between you and MyClassToo.com or its associates. 

<h2>DISPUTES</h2>
Any dispute relating in any way to your visit to MyClassToo.com or to products you purchase through MyClassToo.com shall be submitted to confidential arbitration in California, United States, except that, to the extent you have in any manner violated or threatened to violate MyClassToo.coms intellectual property rights, MyClassToo.com may seek injunctive or other appropriate relief in any state or federal court in the state of California, Unites States, and you consent to exclusive jurisdiction and venue in such courts. Arbitration under this agreement shall be conducted under the rules then prevailing of the American Arbitration Association. The arbitrators award shall be binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under this Agreement shall be joined to an arbitration involving any other party subject to this Agreement, whether through class arbitration proceedings or otherwise. 

<h2>SITE POLICIES, MODIFICATION, AND SEVERABILITY</h2>
Please review our other policies, such as our Shipping and Returns policy, posted on this site. These policies also govern your visit to MyClassToo.com. We reserve the right to make changes to our site, policies, and these Conditions of Use at any time. If any of these conditions shall be deemed invalid, void, or for any reason unenforceable, that condition shall be deemed severable and shall not affect the validity and enforceability of any remaining condition. 

<h2>QUESTIONS:</h2>
Questions regarding our Conditions of Usage, Privacy Policy, or other policy related material can be directed to our support staff by clicking on the "Contact Us" link in the side menu. Or you can email us at: <a href="mailto:info@myclasstoo.com">info@myclasstoo.com</a>. 